text:
  -
    value: "<p><a href=\"[message:author:url:absolute]\">[message:author:display-name]</a> commented on [social_comment:parent_entity_author]'s [social_comment:commented_content_type]</p>\r\n"
    format: full_html
  -
    value: "<p><a href=\"[message:author:url:absolute]\">[message:author:display-name]</a> and @count others commented on [social_comment:parent_entity_author]'s [social_comment:commented_content_type]</p>\r\n"
    format: full_html
