text:
  -
    value: "<p><a href=\"[message:author:url:absolute]\">[message:author:display-name]</a> kommenterte p책 en post p책 din <a href=\"[message:recipient-user-url]\">profil</a></p>\r\n"
    format: full_html
  -
    value: "<p><a href=\"[message:author:url:absolute]\">[message:author:display-name]</a> kommenterte p책 en post p책 din <a href=\"[message:recipient-user-url]\">profil</a></p>\r\n"
    format: full_html
  -
    value: "<p><a href=\"[message:author:url:absolute]\">[message:author:display-name]</a> commented on a post on your <a href=\"[message:recipient-user-url]\">profile</a></p>\r\n"
    format: full_html
