text:
  -
    format: full_html
  -
    format: full_html
    value: "<p><a href=\"[message:author:url:absolute]\">[message:author:display-name]</a> postet p√• din profil</p>\r\n"
  -
    format: full_html
