text:
  -
    format: full_html
    value: '<p><a href="[message:author:url:absolute]">[message:author:display-name]</a> commented on a post in <a href="[message:gurl]">[message:gtitle]</a></p>'
  -
    format: full_html
    value: '<p><a href="[message:author:url:absolute]">[message:author:display-name]</a> and @count others commented on a post in <a href="[message:gurl]">[message:gtitle]</a></p>'
