text:
  -
    value: '<p><a href="[message:author:url:relative]">[message:author:display-name]</a> mentioned you in a comment</p>'
    format: full_html
  -
    value: '<p><a href="[message:author:url:relative]">[message:author:display-name]</a> mentioned you in a comment</p>'
    format: full_html
  -
    value: '<p><a href="[message:author:url:relative]">[message:author:display-name]</a> mentioned you in a <a href="[message:field_message_related_object:entity:url:absolute]">comment</a></p>'
    format: full_html
