text:
  -
    value: '<p><a href="[message:author:url:absolute]">[message:author:display-name]</a> likes your <a href="[social_like:liked_entity]">[social_like:liked_content_type]</a></p>'
    format: full_html
  -
    value: '<p><a href="[message:author:url:absolute]">[message:author:display-name]</a> likes your <a href="[social_like:liked_entity]">[social_like:liked_content_type]</a></p>'
    format: full_html
  -
    value: '<p><a href="[message:author:url:absolute]">[message:author:display-name]</a> likes your <a href="[social_like:liked_entity]">[social_like:liked_content_type]</a></p>'
    format: full_html
description: 'En person liker et innlegg, et emne eller en hendelse opprettet av meg'
