display:
  default:
    display_title: Hoved
    display_options:
      exposed_form:
        options:
          submit_button: Bruk
          reset_button_label: Nullstill
          exposed_sorts_label: 'Sortér på'
          sort_asc_label: Stigende
          sort_desc_label: Synkende
      title: Aktivitetsstrøm
      empty:
        area:
          content:
            value: 'Du har ingen varslinger.'
      arguments:
        field_activity_recipient_user_target_id:
          exception:
            title: Alle
      use_more_text: 'Alle varslinger'
  block_1:
    display_title: Blokk
  page_1:
    display_title: Side
    display_options:
      pager:
        options:
          tags:
            previous: '‹ Forrige'
            next: 'Neste ›'
          expose:
            items_per_page_label: 'Elementer per side'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Forskyving
