display:
  default:
    display_title: Hoved
    display_options:
      exposed_form:
        options:
          submit_button: Bruk
          reset_button_label: Nullstill
          exposed_sorts_label: 'Sortér på'
          sort_asc_label: Stigende
          sort_desc_label: Synkende
      pager:
        options:
          tags:
            previous: '‹ Forrige'
            next: 'Neste ›'
          expose:
            items_per_page_label: 'Elementer per side'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Forskyving
      title: Aktivitetsstrøm
      arguments:
        activity_profile_argument:
          exception:
            title: Alle
  block_1:
    display_title: Blokk
