display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Filtrer
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
          tags:
            previous: '‹ Previous'
            next: 'Next ›'
            first: '« First'
            last: 'Last »'
      fields:
        title:
          separator: ', '
      filters:
        status:
          expose:
            label: 'Publish status'
      title: 'Events for this user'
      empty:
        area_text_custom:
          content: 'No events found for this user'
  block_events_on_profile:
    display_options:
      filters:
        status:
          expose:
            label: 'Publish status'
      title: 'Upcoming events'
  events_overview:
    display_options:
      menu:
        title: Events
      tab_options:
        title: Topics
      filters:
        status:
          expose:
            label: 'Publish status'
        field_event_date_value:
          expose:
            label: 'Start date'
          group_info:
            label: 'Event status'
            group_items:
              1:
                title: 'Upcoming events'
              2:
                title: 'Events that have started or are finished'
