display:
  default:
    display_title: Hoved
    display_options:
      exposed_form:
        options:
          submit_button: Filtrer
          reset_button_label: Nullstill
          exposed_sorts_label: 'Sortér på'
          sort_asc_label: Stigende
          sort_desc_label: Synkende
      pager:
        options:
          expose:
            items_per_page_label: 'Elementer per side'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Forskyving
          tags:
            previous: ‹‹
            next: ››
      fields:
        label:
          separator: ', '
      filters:
        status:
          expose:
            label: Publiseringsstatus
      arguments:
        gid:
          exception:
            title: Alle
  page_group_topics:
    display_title: Side
