display:
  default:
    display_title: Hoved
    display_options:
      exposed_form:
        options:
          submit_button: Bruk
          reset_button_label: Nullstill
          exposed_sorts_label: 'Sortér på'
          sort_asc_label: Stigende
          sort_desc_label: Synkende
      pager:
        options:
          expose:
            items_per_page_label: 'Elementer per side'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Forskyving
          tags:
            previous: ‹‹
            next: ››
      arguments:
        nid:
          exception:
            title: Alle
  event_enrollments:
    display_title: Blokk
    display_options:
      arguments:
        nid:
          exception:
            title: Alle
  view_enrollments:
    display_title: Side
    display_options:
      pager:
        options:
          tags:
            previous: '‹ Forrige'
            next: 'Neste ›'
            first: '« Første'
            last: 'Siste »'
          expose:
            items_per_page_label: 'Elementer per side'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Forskyving
