module:
  activity_basics: 0
  activity_creator: 0
  activity_logger: 0
  activity_send: 0
  activity_send_email: 0
  activity_viewer: 0
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  coffee: 0
  color: 0
  comment: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  config_translation: 0
  config_update: 0
  crop: 0
  datetime: 0
  dblog: 0
  dropdown: 0
  drupalnorge_custom: 0
  dynamic_entity_reference: 0
  editor: 0
  entity: 0
  entity_access_by_field: 0
  features: 0
  features_ui: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  flag: 0
  gnode: 0
  google_analytics: 0
  group: 0
  group_core_comments: 0
  help: 0
  honeypot: 0
  image: 0
  image_effects: 0
  image_widget_crop: 0
  language: 0
  like_and_dislike: 0
  link: 0
  locale: 0
  mailchimp: 0
  mailchimp_signup: 0
  mailsystem: 0
  mentions: 0
  menu_link_content: 0
  menu_ui: 0
  message: 0
  node: 0
  options: 0
  override_node_options: 0
  path: 0
  profile: 0
  r4032login: 0
  reroute_email: 0
  search_api: 0
  search_api_db: 0
  search_api_views_taxonomy: 0
  slack_invite: 0
  social_activity: 0
  social_comment: 0
  social_core: 0
  social_editor: 0
  social_event: 0
  social_file_private: 0
  social_follow_content: 0
  social_font: 0
  social_group: 0
  social_like: 0
  social_mentions: 0
  social_page: 0
  social_post: 0
  social_post_photo: 0
  social_profile: 0
  social_search: 0
  social_swiftmail: 0
  social_topic: 0
  social_tour: 0
  social_user: 0
  sparkpost: 0
  swiftmailer: 0
  system: 0
  taxonomy: 0
  telephone: 0
  template_suggestions_extra: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_infinite_scroll: 0
  views_ui: 0
  votingapi: 0
  views: 10
  improved_theme_settings: 50
  social: 1000
theme:
  stable: 0
  bootstrap: 0
  classy: 0
  socialbase: 0
  seven: 0
  socialblue: 0
  drupalnorge_theme: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
langcode: nb
profile: social
