theme: current
defaults:
  sender: social_swiftmailer
  formatter: social_swiftmailer
_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
modules:
  swiftmailer:
    none:
      formatter: social_swiftmailer
      sender: social_swiftmailer
langcode: nb
