favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: /themes/socialbase/images/favicon/favicon.ico
  use_default: 1
schema: '8000'
features:
  comment_user_picture: true
  comment_user_verification: 1
  favicon: 1
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: 1
region_wells:
  breadcrumb: ''
  hero: ''
  primary_action: ''
  secondary_navigation: ''
  complementary: ''
forms_smart_descriptions: 0
cdn_provider: ''
tooltip_enabled: 0
_core:
  default_config_hash: iySZcWtfipQgBhpW8NcT1Uo95O8XamPlAxa548npgV0
schemas:
  bootstrap: 8000
  socialbase: 8000
langcode: nb
