label: 'Open group: Group node (Event)'
description: 'Adds <em class="placeholder">Event</em> content to groups both publicly and privately.'
group_type: open_group
content_plugin: 'group_node:event'
