label: 'Open group: Group node (Topic)'
description: 'Adds <em class="placeholder">Topic</em> content to groups both publicly and privately.'
group_type: open_group
content_plugin: 'group_node:topic'
