label: 'Request to join a group'
description: 'A person requests membership to a group I manage'
text:
  -
    value: "<p><a href=\"[message:recipient-user:url:absolute]\">[message:recipient-user:display-name]</a> has requested membership to the <a href=\"[message:gurl]\">[message:gtitle]</a> group</p>\r\n"
  -
    value: "<p><a href=\"[message:recipient-user:url:absolute]\">[message:recipient-user:display-name]</a> has requested membership to the <a href=\"[message:gurl]\">[message:gtitle]</a> group</p>\r\n"
  -
    value: "<p><a href=\"[message:recipient-user:url:absolute]\">[message:recipient-user:display-name]</a> has requested membership to the <a href=\"[message:gurl]\">[message:gtitle]</a> group</p>\r\n\r\n<table class=\"btn-wrapp\">\r\n\t<tbody>\r\n\t\t<tr>\r\n\t\t\t<td class=\"align-center\"><a class=\"btn-link btn-link-bg btn-link-one\" href=\"[social_group_request:request_page_link]\">View request</a></td>\r\n\t\t</tr>\r\n\t</tbody>\r\n</table>\r\n"
