label: 'Create post on profile'
description: 'A person created a post on my profile'
text:
  -
    value: |
      <p><a href="[message:author:url:absolute]">[message:author:display-name]</a> posted on your profile</p>
  -
    value: |
      <p><a href="[message:author:url:absolute]">[message:author:display-name]</a> posted on your profile</p>
  -
    value: '<p><a href="[message:author:url:absolute]">[message:author:display-name]</a> posted on your <a href="[message:recipient-user-url]">profile</a></p><p>[message:additional_information]</p>'
