label: 'Information about an index'
tips:
  search-api-index-introduction:
    label: 'Information about an index'
    body: 'This page shows a summary of a search index and its status.'
  search-api-index-index-status:
    label: 'Index status'
    body: 'This gives a summary about how many items are known for this index, and how many have been indexed in their latest version. Items that are not indexed yet cannot be found by searches.'
  search-api-index-status:
    label: Status
    body: 'Shows whether the index is currently enabled or disabled.'
  search-api-index-datasources:
    label: Datasources
    body: 'Lists all datasources that are enabled for this index.'
  search-api-index-tracker:
    label: Tracker
    body: 'The tracker used by the index. Only one ("Default") is available by default.'
  search-api-index-server:
    label: Server
    body: 'If the index is attached to a server, this server is listed here.'
  search-api-index-server-index-status:
    label: 'Server index status'
    body: 'For enabled indexes, the number of items that can actually be retrieved from the server is listed here. For reasons why this number might differ from the number under "Index status", <a href="https://www.drupal.org/docs/8/modules/search-api/getting-started/frequently-asked-questions#server-index-status">see the module''s documentation</a>.'
  search-api-index-cron-batch-size:
    label: 'Cron batch size'
    body: 'The number of items that will be indexed at once during cron runs.'
  search-api-index-index-now:
    label: 'Start indexing now'
    body: 'The "Start indexing now" form allows indexing items manually right away, with a batch process. Otherwise, items are only indexed during cron runs. The form might be disabled if indexing is currently not possible for some reason, or not necessary.'
  search-api-index-tracking:
    label: 'Track items for index'
    body: 'In certain situations, the index''s tracker doesn''t have the latest state of the items available for indexing. This will be automatically rectified during cron runs, but can also be manually triggered here, with the "Track now" button.'
  search-api-index-reindex:
    label: 'Queue all items for reindexing'
    body: 'This will queue all items on this index for reindexing. Previously indexed data will remain on the search server, so searches on this index will continue to yield results.'
  search-api-index-clear:
    label: 'Clear all indexed data'
    body: 'This will remove all indexed content for this index from the search server and queue it for reindexing. Searches on this index will not return any results until items are reindexed.'
