label: 'Group Members'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      fields:
        label:
          separator: ', '
      title: 'Group Members'
      empty:
        area:
          content:
            value: 'No memebers in this group'
      arguments:
        gid:
          exception:
            title: All
  block_newest_members:
    display_title: Block
    display_options:
      title: 'Newest Members'
      empty:
        area_text_custom:
          content: 'No memebers in this group'
  page_group_members:
    display_title: Page
