label: 'Activity Stream'
display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: ‹‹
            next: ››
          expose:
            items_per_page_label: 'Items per page'
            items_per_page_options_all_label: '- All -'
            offset_label: Offset
      title: Stream
  block_stream_homepage:
    display_title: 'Homepage stream block'
  block_stream_homepage_without_post:
    display_title: 'Homepage stream block'
  page_activity_stream:
    display_title: Page
  page_explore:
    display_title: Explore
    display_options:
      display_description: 'Explore page for LU'
      header:
        entity_block:
          admin_label: header_postblock
      title: 'Explore Stream'
